FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY src/ ./src/
COPY artifacts/ ./artifacts/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]